server:
  servlet:
    session:
      timeout: 10m
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  properties:
    authboot-credentials: ${AUTHBOOT_CREDENTIALS:sysadmin:sysadmin}
    auth-url: ${AUTH_URL:http://localhost:8090}
    backend-url: ${BACKEND_URL:http://localhost:8091}
    feign:
      auth: ${spring.properties.auth-url}/api
      cars: ${spring.properties.backend-url}/api/cars
      clients: ${spring.properties.backend-url}/api/clients
      payment: ${spring.properties.backend-url}/api/reservations
      reservations: ${spring.properties.backend-url}/api/reservations
      subsidiaries: ${spring.properties.backend-url}/api/subsidiaries
  cloud:
    openfeign:
      okhttp:
        enabled: true


