server:
  error:
    whitelabel:
      enabled: false
    path: /error
spring:
  properties:
    auth-url: ${AUTH_URL:http://localhost:8090}
    backend-url: ${BACKEND_URL:http://localhost:8091}
    feign:
      auth: ${spring.properties.auth-url}/api
      cars: ${spring.properties.backend-url}/api/cars
      payment: ${spring.properties.backend-url}/api/payments
      reservations: ${spring.properties.backend-url}/api/reservations
      subsidiaries: ${spring.properties.backend-url}/api/subsidiaries
  cloud:
    openfeign:
      okhttp:
        enabled: true


